### PR TITLE
chore: use common logos in readme

### PR DESCRIPTION
**Pull request by JuroUhlar**

### CODE REVIEW

**Review by ilfa — DISMISSED** [review]
We will break old versions in the npm, just for the info

**Comment by JuroUhlar** [comment]
> We will break old versions in the npm, just for the info

But it will be fixed with the next NPM release? We can merge this is sync with the next one

**Comment by ilfa** [comment]
> But it will be fixed with the next NPM release? We can merge this is sync with the next one

I meaned previous versions [like this](https://www.npmjs.com/package/@fingerprintjs/fingerprintjs-pro-server-api/v/2.3.1)

Also for the release you need to rename first commit `chore: use common logos in readme` -> `docs(README): use common logos in readme`

**Comment by JuroUhlar** [comment]
> > But it will be fixed with the next NPM release? We can merge this is sync with the next one
> 
> I meaned previous versions [like this](https://www.npmjs.com/package/@fingerprintjs/fingerprintjs-pro-server-api/v/2.3.1)
> 
> Also for the release you need to rename first commit `chore: use common logos in readme` -> `docs(README): use common logos in readme`

I rebased the branch to keep just the one commit with the proper message. I restored the images so we avoid breaking old Readme versions.

**Review by ilfa — APPROVED** [review]

**Pull request merged**
